
import { Pizza } from './types';

export const INITIAL_PIZZAS: Pizza[] = [
  // PIZZAS
  {
    id: 'p1',
    name: 'Маргарита',
    description: 'соус томатний, сир Моцарелла, помідор, зелена олія.',
    price: 99,
    image: 'https://images.unsplash.com/photo-1574071318508-1cdbad80ad38?auto=format&fit=crop&q=80&w=800',
    category: 'pizza',
  },
  {
    id: 'p2',
    name: 'Курка Гриби',
    description: 'соус вершковий, сир Моцарелла, курка маринована, печериці, цибуля маринована, зелена олія.',
    price: 159,
    image: 'https://images.unsplash.com/photo-1565299624946-b28f40a0ae38?auto=format&fit=crop&q=80&w=800',
    category: 'pizza',
  },
  {
    id: 'p3',
    name: 'Мисливська',
    description: 'соус томатний, ковбаски мисливські, салямі баликова, огірок маринований, перець халапеньо, сир Моцарелла, цибуля маринована, соус BBQ.',
    price: 159,
    image: 'https://images.unsplash.com/photo-1541745537411-b8046dc6d66c?auto=format&fit=crop&q=80&w=800',
    category: 'pizza',
  },
  {
    id: 'p4',
    name: 'Франческа',
    description: 'соус томатний, бекон, салямі баликова, печериці, сир Моцарелла, помідор, маслини, зелена олія.',
    price: 159,
    image: 'https://images.unsplash.com/photo-1513104890138-7c749659a591?auto=format&fit=crop&q=80&w=800',
    category: 'pizza',
  },
  {
    id: 'p5',
    name: 'Гавайська',
    description: 'соус вершковий, курка маринована, ананас, цибуля маринована, сир Моцарелла.',
    price: 169,
    image: 'https://images.unsplash.com/photo-1565299585323-38d6b0865b47?auto=format&fit=crop&q=80&w=800',
    category: 'pizza',
  },
  {
    id: 'p6',
    name: '4 Сири',
    description: 'соус вершковий, сир Моцарелла, сир твердий, сир Дор Блю, сир Пармезан.',
    price: 169,
    image: 'https://images.unsplash.com/photo-1573821663912-56990544c381?auto=format&fit=crop&q=80&w=800',
    category: 'pizza',
    isPromo: true,
  },
  {
    id: 'p7',
    name: 'Карбонара',
    description: 'соус вершковий, бекон, сир Моцарелла, цибуля маринована, яйце, сир Пармезан, перець чорний.',
    price: 169,
    image: 'https://images.unsplash.com/photo-1628840042765-356cda07504e?auto=format&fit=crop&q=80&w=800',
    category: 'pizza',
  },
  {
    id: 'p8',
    name: 'Цезар',
    description: 'соус вершковий, курка маринована, сир Моцарелла, сир Пармезан, капуста Айсберг, помідор, соус Цезар.',
    price: 179,
    image: 'https://images.unsplash.com/photo-1513104890138-7c749659a591?auto=format&fit=crop&q=80&w=800',
    category: 'pizza',
  },
  {
    id: 'p9',
    name: 'Максі М’ясо',
    description: 'соус BBQ, сир Моцарелла, ковбаски мисливські, курка маринована, салямі баликова, бекон, цибуля маринована, часникова олія, помідор.',
    price: 179,
    image: 'https://images.unsplash.com/photo-1541745537411-b8046dc6d66c?auto=format&fit=crop&q=80&w=800',
    category: 'pizza',
    isNew: true,
  },
  {
    id: 'p10',
    name: 'Сирна з грушею та Дор Блю',
    description: 'соус вершковий, сир Моцарелла, сир Дор Блю, груша, волоські горіхи, медово-гірчичний соус, Пармезан.',
    price: 189,
    image: 'https://images.unsplash.com/photo-1564936281291-294551497d81?auto=format&fit=crop&q=80&w=800',
    category: 'pizza',
  },
  {
    id: 'p11',
    name: 'Пепероні',
    description: 'соус томатний, ковбаса пепероні/чорізо, перець халапеньо, сир Моцарелла.',
    price: 195,
    image: 'https://images.unsplash.com/photo-1628840042765-356cda07504e?auto=format&fit=crop&q=80&w=800',
    category: 'pizza',
  },
  {
    id: 'p12',
    name: 'Шпинатна з грибами',
    description: 'соус вершковий, шпинат, сир Моцарелла, сир Дор Блю, печериці, соус Теріякі.',
    price: 169,
    image: 'https://images.unsplash.com/photo-1593560708920-61dd98c46a4e?auto=format&fit=crop&q=80&w=800',
    category: 'pizza',
  },
  {
    id: 'p13',
    name: 'Тунець з Пармезаном',
    description: 'соус томатний, тунець консервований, цибуля маринована, помідор, сир Пармезан, зелена олія.',
    price: 189,
    image: 'https://images.unsplash.com/photo-1571407970349-bc81e7e96d47?auto=format&fit=crop&q=80&w=800',
    category: 'pizza',
  },
  {
    id: 'p14',
    name: 'Кріспі-Бекон',
    description: 'соус вершковий, курка маринована, бекон, мариновані гриби опеньки, сир твердий, сир Моцарелла, кріспі цибуля, рукола, зелена олія.',
    price: 189,
    image: 'https://images.unsplash.com/photo-1541745537411-b8046dc6d66c?auto=format&fit=crop&q=80&w=800',
    category: 'pizza',
  },
  {
    id: 'p15',
    name: 'Американська сирна',
    description: 'соус вершковий, цибуля маринована, свинина маринована, салямі, сир твердий, сир Моцарелла, печериці, кукурудза, сир Чеддер, соус сирний.',
    price: 199,
    image: 'https://images.unsplash.com/photo-1534308983496-4fabb1a015ee?auto=format&fit=crop&q=80&w=800',
    category: 'pizza',
  },
  {
    id: 'p16',
    name: 'Авторська P2P',
    description: 'соус BBQ, цибуля маринована, свинина маринована, сир Моцарелла, ковбаски мисливські, огірок маринований, кукурудза, перець болгарський, маслини, соус Теріякі.',
    price: 259,
    image: 'https://images.unsplash.com/photo-1513104890138-7c749659a591?auto=format&fit=crop&q=80&w=800',
    category: 'pizza',
  },

  // BOX MENU
  {
    id: 'b1',
    name: 'Сирний Хліб',
    description: 'соус вершковий, сир Моцарелла, зелена олія. 240г.',
    price: 69,
    image: '', // Image removed as requested
    category: 'box',
  },
  {
    id: 'b2',
    name: 'М’ясна TO GO',
    description: 'соус томатний, курка маринована, ковбаски мисливські, цибуля маринована, огірок маринований, печериці, сир Моцарелла, сир Чеддер, рукола, соус бургерний.',
    price: 119,
    image: 'https://images.unsplash.com/photo-1551782450-a2132b4ba21d?auto=format&fit=crop&q=80&w=400',
    category: 'box',
  },
  {
    id: 'b3',
    name: 'Картопля печена',
    description: 'картопля соломкою, зелена олія, соус BBQ. 240г.',
    price: 89,
    image: 'https://images.unsplash.com/photo-1585109649139-366815a0d713?auto=format&fit=crop&q=80&w=400',
    category: 'box',
  },
  {
    id: 'b4',
    name: 'Картопля "Кріспі-Бекон"',
    description: 'картопля печена, бекон, цибуля кріспі, соус Цезар, соус Барбекю. 250г.',
    price: 129,
    image: '', // Image removed as requested
    category: 'box',
  },
  {
    id: 'b5',
    name: 'Картопля печена з м\'ясом та сиром',
    description: 'картопля соломкою, свинина маринована, цибуля маринована, сир Моцарелла, соус Цезар, соус BBQ. 350г.',
    price: 149,
    image: 'https://images.unsplash.com/photo-1623238913973-21e45cced554?auto=format&fit=crop&q=80&w=400',
    category: 'box',
  },
  {
    id: 'b6',
    name: 'Нагетси запечені (9 шт)',
    description: 'шматочки курятини в хрумкій паніровці. Подаються гарячими.',
    price: 139,
    image: 'https://images.unsplash.com/photo-1562967914-6c827383d944?auto=format&fit=crop&q=80&w=400',
    category: 'box',
  },
];
